import type { Metadata } from "next";
import { Arimo } from "next/font/google";
import { Libre_Caslon_Display } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";

const arimo = Arimo({ variable: "--arimo", subsets: ["latin"] });
const libre = Libre_Caslon_Display({
  variable: "--libre",
  weight: "400",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn("font-sans antialiased", arimo.variable, libre.variable)}
      >
        {children}
      </body>
    </html>
  );
}
